Update layout
Calindra/solana-twitter pull request #13
Opened 2023-01-24 15:07 UTC by SandHilt

Based on: https://www.figma.com/file/W1SnRSEjYDnszAFJ2JWT5f/Cartesi?node-id=4%3A334&t=wRRIY6vK1MVwJOqU-0

2023-01-24 16:48 UTC, fabiooshiro commented
Está estranho pra mim.
![image](https://user-images.githubusercontent.com/218768/214355501-dea51666-b706-48ac-984a-90e95e94e159.png)

Outra coisa como ficam as NFTs que eu já tenho?

2023-01-24 16:50 UTC, fabiooshiro requested changes
Está diferente do que o f3 desenhou...

2023-01-24 16:51 UTC, fabiooshiro requested changes

2023-01-24 16:51 UTC, fabiooshiro commented on app/src/components/PageProfile.vue
> +// import NFTList from '@/components/NFTList'
Como vc está listando as NFTs que o usuário já possui?
Muita gente compra uma NFT no opensea ou magiceden e coloca como pfp...

2023-01-24 16:58 UTC, SandHilt commented on app/src/components/PageProfile.vue
> +// import NFTList from '@/components/NFTList'
O Vue não reclamou, esqueci de descomentar.
Só o eslint que reclamava.

2023-01-24 18:21 UTC, SandHilt commented
> Está diferente do que o f3 desenhou...

São duas telas, uma de perfil (que foi o que você mostrou a tela) e outra para adicionar a foto.
A de adicionar a foto aparece quando você clica no botão para atualizar.
Posso mudar o endereço da wallet pra lá também, sem problema.

2023-01-25 13:53 UTC, fabiooshiro commented
Agora sim! A gente não tem o remover, mas acho que está ok.

2023-01-25 13:56 UTC, fabiooshiro approved these changes

2023-01-25 13:56 UTC, fabiooshiro commented
lfg!

2023-01-25 18:37 UTC, merged